### ISSUE TITLE
BB_ADMIN_USER_EMAIL + BB_ADMIN_USER_PASSWORD aren't working as intended for self-hosted setups

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13413]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.22.16
  - App Version: 2.22.16
**Describe the bug**
No user is created which can be used to login to Budibase whenever spinning down your BB instance. Adding the above env variables and then spinning up your instance again.

**To Reproduce**
1. Bring down your docker installation
2. Add the Title env variables with relevant values
3. Spin up your docker instance
4. Try and login with the user created
5. See invalid creds, user can't login as the specified user.

**Expected behavior**
Should be able to login with the .env credential user

**Screenshots**
.env
<img width="284" alt="Screenshot 2024-04-05 at 10 52 39" src="https://github.com/Budibase/budibase/assets/126772285/2962fd0d-fd9b-4951-bf91-129ee04b998a">

<img width="1512" alt="Screenshot 2024-04-05 at 10 52 55" src="https://github.com/Budibase/budibase/assets/126772285/0f90619e-c84d-470e-85c7-2319f2576599">

**Comment by mike12345567** [comment]
Fixed in 2.22.17.

**Comment by Raman236** [comment]
Hi

This is not fixed: 

<img width="1482" height="888" alt="Image" src="https://github.com/user-attachments/assets/235d2f14-44b8-47c3-bfad-253ea13e7035" />

I have tried self hosting on my home server using coolify, I got "Invalid Credentials"
I tried using dokploy on my Hetzner Server. I got "Invalid Credentials"
I tries with and without assigning admin user and email in teh docker file.
I am trying from yesterday.

Still doesnt work
