### ISSUE TITLE
Relationship picker errors - [object Object]

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#15480]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 3.4.0
  - App Version: 3.4.0

**Describe the bug**
The relationship picker component is behaving odd. In the UI it is now showing a second line with just [object Object] in it.
![Image](https://github.com/user-attachments/assets/8d9dae52-54fd-4337-9eb5-397a4662eba9)
And I suspect this is also causing the error dialog to be show
![Image](https://github.com/user-attachments/assets/034838b3-9069-484d-a8d3-396a14c5f181)

Console shows these two errors both with the [object Object] references in the path
![Image](https://github.com/user-attachments/assets/d9094031-8c89-40d6-a0ad-0be9bdc28a47)

**To Reproduce**
1. Create an internal db table (table 1) and give it a text field
2. Create another internal table (relationship) and give it a text field
3. Create a relationship from table 1 to the relationship table and populate some example rows in both
4. Create a page and add a new form block linked to table 1

**Expected behavior**
The realationship picker should just show the selected field from the relationship table, but it shows the extra [object Object] part

**Comment by andz-bb** [comment]
hey @andyburgessmd, thanks for raising this, it should now be fixed in #15481 which was released in 3.4.1 earlier today

**Comment by andyburgessmd** [comment]
@andz-bb thanks, this has fixed the relationship picker but I am still getting the "CouchDB error: missing" message. And still see this in the console
![Image](https://github.com/user-attachments/assets/4d72741e-98c4-46cd-b726-432b43c0ef7c)
