### ISSUE TITLE
Automations - steps result disappear although the automation ran correctly

### ISSUE THREAD

**Issue by esellier** [Budibase/budibase#15872]
**Hosting**
- Self
  - Method: Docker compopse
  - Budibase Version: 3.7.2

**Describe the bug**
In many cases, when I run tests on automation, the test details will not appear and I only get the "Trigger step" (only one step appears in the side panel).
But that occurs, sometimes and without explanation. I observed it could be related to the automation duration, but that's not even sure.
Problem is the same if I check Automations results in Settings/Automations.

**To Reproduce**
No idea.... it's juste random. Maybe related to the automation duration??

**Expected behavior**

**Screenshots**
<img width="968" alt="Image" src="https://github.com/user-attachments/assets/fa08f704-870f-41fc-bdb1-6ca3f4420348" />

<img width="974" alt="Image" src="https://github.com/user-attachments/assets/49a15268-6d38-432d-8fe1-a972e1cf0ec8" />

**Comment by ConorWebb96** [comment]
Hey @esellier,

Can you update to the latest version and try again. I'm pretty sure this issue was fixed at some point between your version and the latest version.

**Comment by Stropdasman** [comment]
We just updated to latest version because our automations weren’t working properly. We've encountered the same issue again — even after the update, the problem persists.

Specifically, the "Collect Data" step in our automation doesn’t return any results, which causes our app to break. It seems like the data collection is failing entirely.
This is what we got back: {"data":[""],"pagination":{"cursor":null},"raw":"","headers":{"content-type":"application/json; charset=utf-8","date":"Fri, 04 Apr 2025 09:24:35 GMT","vary":"Accept-Encoding","connection":"close","transfer-encoding":"chunked"},"code":200,"size":"0B","time":"151ms"}

We would expect the output of: 
```
if ($("steps.JavaScript.value") && $("steps.JavaScript 2.value")){
  return 200
}
return 404
```

![Image](https://github.com/user-attachments/assets/3aa71cb3-cf58-4392-a41b-ce9ded4950ad)

**Comment by esellier** [comment]
Still have the same issue on BB 3.8.4
And we are unable now to view tests logs when testing an automation in builder. If I click on the Logs icon (beside Run test), then I'm redirected to the automations logs view which do not include tests.
And the "Data out" tab in step details, says "This step was not executed as part of the test run"... which is not possible as it is the really first step.

**Comment by Stropdasman** [comment]
@esellier For us it was a license issue. When we refreshed the plan it worked.

<img width="1342" alt="Image" src="https://github.com/user-attachments/assets/36cd28f2-ea67-4f5f-981d-06fc584153ff" />
