### ISSUE TITLE
SQL relationship does not seem to work

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2167]
I may be misunderstanding something here, but when I create a relationship of "one", it does not seem to save my foreign key column properly.

Then, when I try to browse the table it looks for the key that I originally chose, but on the wrong table.

Here is my table structure:

![image](https://user-images.githubusercontent.com/3524181/127461929-d1c287be-d827-4cf0-ad9c-347452bd8d01.png)

Here is a demo:

https://user-images.githubusercontent.com/3524181/127461867-d41d8967-45fc-46ab-b200-ddda360d55e6.mp4

Using postgres.

**Comment by shogunpurple** [comment]
@mjashanks do you have display columns set on both of your tables? Me and @mike12345567 were just looking into this and it seems to work if the display columns are set.

**Comment by jheiselman** [comment]
I'm having the same issue that I was before. I have an external MySQL database I'm connected to. Two tables have a fairly basic structure:

host table

id | name
-- | --
1234 | testhost

host_blackout table with foreign key constraint to host.id from host_blackout.host_id

id | host_id | inserted
-- | -- | --
9876 | 1234 | 2021-07-30 10:20:00


The two tables in question have their display columns set. When I create the relationship in Budibase, I use the following settings:

Relationship type: One
From table: host
To table: host_blackout
Foreign Key: host_id
From table column: maintenance_since
To table column: host_name

Once I save the relationship, if I open it again, it appears that Budibase changed the foreign key to the "id" column in the host_blackout table. When I load up the host_blackout table view, the host_name column is null for each record and when I try to load up host table view, it just hangs.

Looking into the stdout in the container, the SQL is clearly using host_blackout.id in the left join statement. I can't seem to get it to accept the host_id column for that foreign key.

I'm running the latest image tag pulled as of this morning.

**Comment by mike12345567** [comment]
Hi @jheiselman - just to check, have you updated your display columns? This is a bit confusing and we plan to update the UI to make this more obvious, but Budibase needs a display column for it to display the relationship between the two different tables.

The fact the foreign key is switching to the `id` field does sound like there is another bug, but just wondering if this is the case.

You can set it with the button here:
![image](https://user-images.githubusercontent.com/4407001/127688947-1ed3a6cd-e633-4fe4-a2fc-49bf423e4493.png)

**Comment by jheiselman** [comment]
@mike12345567 yes, they are set

**Comment by mike12345567** [comment]
Thanks for the info @jheiselman - i've created your table structure in my environment and can see it happening, will get a fix for it.

**Comment by mjashanks** [comment]
Here are mine if you need them...

```
-- Table: public.customers

-- DROP TABLE public.customers;

CREATE TABLE IF NOT EXISTS public.customers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    age integer,
    "dateOfBirth" date,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.customers
    OWNER to postgres;

-- Table: public.deals

-- DROP TABLE public.deals;

CREATE TABLE IF NOT EXISTS public.deals
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    value double precision,
    "customerId" integer,
    CONSTRAINT id_key PRIMARY KEY (id),
    CONSTRAINT to_customers FOREIGN KEY ("customerId")
        REFERENCES public.customers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.deals
    OWNER to postgres;
```

**Comment by mike12345567** [comment]
@jheiselman A fix has been merged for this, will be released shortly, if you could update once the release is available and let me know if this resolves your issue that'd be great.

**Comment by jheiselman** [comment]
@mike12345567 it's partially fixed. It now respects the foreign key choice and it seems to work with creating a relationship. However, in the table view it still doesn't show the value from the configured display column for the foreign record. But, also, when editing the row, the default display value appears to be garbled, but the drop-down list is correct AND choosing a value from the list does appropriately update the record once saved.

**Comment by mike12345567** [comment]
Interesting @jheiselman - could you provide some screenshots of the behaviour you're seeing?

Also it would be great if you could provide an example of the table schema you'd using, for example if you have a distilled example with `CREATE TABLE` syntax it would be a lot easier for me to replicate. I created a table myself from the schema you described above with a `hosts` and `host_blackouts` table, with a relationship as you described, but I experienced no issues with this.

**Comment by jheiselman** [comment]
The database I'm testing it against is something for work, so I can't provide a full dump without going through some efforts that no one is interested in. However, here is a minimal example:

```
CREATE TABLE `host` (
  `id` bigint(20 unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
) ENGINE=InnoDB AUTO_INCREMENT=8948 DEFAULT CHARSET=latin1;

INSERT INTO `host` VALUES (178, `testhost`);

CREATE TABLE `host_blackout` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `host_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `host_id` (`host_id`),
  CONSTRAINT `host_blackout_ibfk_1` FOREIGN KEY (`host_id`) REFERENCES `host` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1108 DEFAULT CHARSET=latin1;
```

I will have to supply screen shots on Monday at this time in the day, but hopefully you can work out the issue from there.
Just to clarify the issue I'm seeing, after adding the relationship in Budibase, I go to the host_blackouts table view in the Data page, it loads all the data from the database and it adds the column `host` as I've told it too, however, that column is empty for all of the entries. If I edit one of them, the drop-down is populated properly, but the default selected entry appears to be garbled. I'll have to grab a screen shot of that. This is all before I get to the design phase for my Budibase app.

**Comment by mike12345567** [comment]
@jheiselman thanks for the example, that's incredibly helpful, I should be able to recreate from this!

**Comment by mike12345567** [comment]
I have played around with the examples in this thread, a release has gone out with some changes that should fix all of the problems that were being had.

**Comment by jheiselman** [comment]
I have confirmed that this resolved my issue. Thank you @mike12345567
