### ISSUE TITLE
Form for "Request access to Cloud Sandbox"  is broken

### ISSUE THREAD

**Issue by huyz** [Budibase/budibase#2846]
**Describe the bug**
As soon as I click on the "Request access to Cloud Sandbox" button, it says "Session has expired.
So can't sign up on the form.
Not only do some pulldowns have no options listed. JS console shows a 403

![image](https://user-images.githubusercontent.com/128394/135631016-98e07eec-fdd0-40ee-b72d-04508734eb37.png)

**Comment by qaribhaider** [comment]
Bump

**Comment by joebudi** [comment]
I'll have a look at this within the hour

**Comment by joebudi** [comment]
That should be it sorted

**Comment by joebudi** [comment]
Fixed - we moved our company cloud account and forgot to update the URL on the website.

**Comment by huyz** [comment]
@joebudi You updated the banner, but you missed the white button "Request access to Cloud Sandbox".

**Comment by joebudi** [comment]
You are right. Thanks!
