### ISSUE TITLE
Budibase rewrites the URL to have port 10000 when connecting through a reverse proxy

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4448]
**Describe the bug**
Budibase rewrites the URL to have port 10000 when connecting through HAproxy, directly connecting via IP works as expected.

**To Reproduce**
1. Run `budi hosting --init`
2. Press Y then enter a non default port (e.g. 80)
3. run `budi hosting --start`
4. Connect to budibase with the non default port (e.g http://127.0.0.1)
5. Budibase should greet you with a login page
6. Setup a reverse proxy with HAproxy (or your reverse proxy of choice) so that it connects to budibase on the port you set earlier
7. Try connecting to Budibase through the reverse proxy
8. The URL will be rewritten to http://hostname.com:10000/builder and will not work

**Expected behavior**
The URL should match the platform URL set in organisation settings

**Additional context**
Budibase version: 1.0.62

**Comment by shogunpurple** [comment]
Hi @FlaminWrap - the latest update should fix this. Please pull the latest docker images either manually with:

`docker-compose pull && docker compose up`

Or run using the budi CLI

`budi hosting —update`

Let us know if that isn’t working for you and I will debug further. 

Thanks!

**Comment by mike12345567** [comment]
Hi @FlaminWrap just to say as well, you will need to get the latest CLI version for this to work, older versions of the CLI don't update the proxy image correctly.

**Comment by FlaminWrap** [comment]
Thanks for the response guys.

Made sure that I was on the latest budi-cli through npm and did `budi hosting --update`. That did not fix it.
![image](https://user-images.githubusercontent.com/97764630/153721719-5700c53f-ef34-4161-8e91-65f3e8ee474b.png)

Did `docker-compose pull && docker compose up` and this was being output every second or so. 10.1.25.254 is the reverse proxy server.
![image](https://user-images.githubusercontent.com/97764630/153721292-3c854eec-04f5-452d-96a1-7d2f6f14521c.png)

**Comment by FlaminWrap** [comment]
Just like to comment that it now works. I am using PFsense HAproxy for the reverse proxy, checking the "Use Client-IP to connect to backend servers" option in the backend settings made it work.
