### ISSUE TITLE
Error whilst adding new user

### ISSUE THREAD

**Issue by usamamumtaz1** [Budibase/budibase#4528]
hi
i m getting the attached error whilst adding a new user to my app.  this is the first time i am seeing this iissue

can you please help?

![2022-02-16 at 13 46](https://user-images.githubusercontent.com/96530344/154277780-51d06fec-caa9-4d46-86c1-1812d3330bef.png)

**Comment by aptkingston** [comment]
Hey @usamamumtaz1. We just merged a fix for this a couple of minutes ago:
https://github.com/Budibase/budibase/pull/4526

We'll get it released soon.

**Comment by usamamumtaz1** [comment]
brilliant, thank you so much

**Comment by usamamumtaz1** [comment]
just wanted to follow up on this, i am still seeing the same error. any ETA ? @aptkingston
