### ISSUE TITLE
Entering formula crashes the app

### ISSUE THREAD

**Issue by Hajelarohit** [Budibase/budibase#5664]
**Hosting**

- Self
  - Budibase Version: <1.0.110> 

**Describe the bug**
When i am creating a new column in table using formula as the type, as soon as I enter the formula the budibase crashes.

Step 1 - Create a new column in table, choose formula as type
![image](https://user-images.githubusercontent.com/104535363/166069919-22b16b88-6984-40ed-b7a3-b1952971528d.png)

Step 2 - Enter Formula, click confirm
![image](https://user-images.githubusercontent.com/104535363/166070046-d796559d-e9be-43b7-ae3a-8392f0754df7.png)

Result - BudiBase not responding
![image](https://user-images.githubusercontent.com/104535363/166070151-25539da4-68f4-4e36-bd54-eccc8df2275e.png)
![image](https://user-images.githubusercontent.com/104535363/166070203-4b3491e8-0ac5-4fb1-9007-ce699c64dda0.png)

after i hit refresh, it takes me back to the original table.

All I am trying to do it get the vendor name from the relational table (other table) and store in this table as a reference.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [Version 100.0.1185.50 (Official build) (64-bit)]

**Comment by zimmra** [comment]
It's because the formula is invalid. The helpers don't insert the correct helper. It is fixed in a future release, whenever pr https://github.com/Budibase/budibase/pull/5542 gets pushed into the release it'll work as expected

It should be 
```
{{ VID_Sub.0.Vendor Name }}
```
You can manually type that in and see if it works

**Comment by Hajelarohit** [comment]
Hi Zimmra
I tried that forumla, but it still crashed and keeps crashing every time i enter anything in the formula field.

**Comment by Hajelarohit** [comment]
Can someone please help? I can't use the relationship table if I can't get the relationship columns in another table via a formula.

for example, i have a supplier table that has supplier details and a Supplier ID. I have another table for supplier products and a relationship column (Supplier ID) to the first table. Now when i am using the second table, i want my user to know that this product from this supplier ID is from a certain supplier. I tried using the formula to add a column from relationship name, but it crashes the app. I am stuck now.

**Comment by melohagan** [comment]
Hi @Hajelarohit 

If there's no sensitive data, are you able to provide the app export? Are you using the Internal Budibase DB?

**Comment by mike12345567** [comment]
Hi @Hajelarohit - this has been fixed in the version which is slated for release this week, I tested your app with this formula:
![image](https://user-images.githubusercontent.com/4407001/166690096-134f05e5-01ed-44a6-8d1b-7ddc4103953d.png)

Which produced this:
![image](https://user-images.githubusercontent.com/4407001/166690150-be2918bc-cfe4-477f-bedd-822469b307e8.png)

The syntax shown for relationships in your version of Budibase isn't quite right and there was some issues with how it was processed.

**Comment by Hajelarohit** [comment]
Thanks Mike, much appreciated. Can you share the date of the next release? I can't wait to try it on the new version :)

**Comment by mike12345567** [comment]
Hi @Hajelarohit - it should be today or tomorrow. We are just performing some final QA and then it will be released.

**Comment by Hajelarohit** [comment]
So it worked for that table. however when i am trying to add the same formula to other tables, it is not pulling the  information

![image](https://user-images.githubusercontent.com/104535363/166961195-43c900c9-5a6b-4ca6-91d2-09f361199f52.png)

![image](https://user-images.githubusercontent.com/104535363/166961420-3822d35f-fffd-4fe4-8b95-5b976dbfe659.png)

I chose the formula from the options on the left. As soon as i select the formula, the submit button gets disabled.
![image](https://user-images.githubusercontent.com/104535363/166961569-481515b0-56af-487f-846a-81150458c557.png)

**Comment by Hajelarohit** [comment]
Hi Mike, not sure how to interpret this information and fix it in my app. I am not a coder, that's why i am using budibase :-)

**Comment by mike12345567** [comment]
Hi @Hajelarohit - sorry I should have said, this was to release a fix to how bindings are generated, in the version released today if you wipe your broken formula bindings and re-create them it should be resolved.

**Comment by Hajelarohit** [comment]
Hi @mike12345567, It is crashing again. I tried to enter a formula from the same table and also another relationship table, it crashes the app.
