### ISSUE TITLE
New Account cannot create App

### ISSUE THREAD

**Issue by ChristopherPeterFrank** [Budibase/budibase#5738]
Type: Cloud hosted

Issue: New account created and verified earlier today. 
Cannot create app from template or scratch.  I receive the message "Error Creating App".  See attached and thank-you in advance.
![Screenshot_20220505-225221_Chrome](https://user-images.githubusercontent.com/12631947/167059198-9b3f3b7f-e171-4779-ada9-a559bb5e3098.jpg)

**Comment by shogunpurple** [comment]
Thanks @ChristopherPeterFrank - would you be able to show me what is in the browser dev tools?

- Right click, and "Inspect Element"
- Go to the "Network" tab
- Try and create an app
- You should see a call to `applications`, click that and go to "Response"
- Drop that screenshot into this issue.

This will really help us to debug and find what the issue is. Thanks!

**Comment by ChristopherPeterFrank** [comment]
Hi Martin,

Here is the response.

Google Chrome:
Version 100.0.4896.127 (Official Build) (64-bit)

[image: image.png]
Christopher Frank
R. Denninger Limited
(905) 516 2047

**Comment by shogunpurple** [comment]
Hi @ChristopherPeterFrank - I can't see the image, it doesn't seem to be appearing. You could send the screenshot directly to `support@budibase.com` if the github email integration is giving you trouble.

**Comment by Rory-Powell** [comment]
Hi @ChristopherPeterFrank, we found the root cause on this which was related to the name that was chosen for your budibase URL. We use the term `app` internally when creating the unique database for each application, in this case the suffix from the tenant id, which is the end of your budibase url - retail**app** - was causing an error. 

We'll track the fix here: https://github.com/Budibase/budibase/issues/5778 

For now the easiest workaround would be to create an account from scratch with a different url. You can delete the existing account here https://account.budibase.app/portal/account if you need to use your existing email address.

**Comment by marcogutama** [comment]
Hello. Same error. New account, can not create app
<img width="931" alt="image" src="https://user-images.githubusercontent.com/16564571/186319488-5ec50f64-9962-4a28-87ca-890e90b6e817.png">

**Comment by marcogutama** [comment]
I attach response from dev tools when creating app:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/16564571/186322040-8bb1f679-e399-4b6d-bb56-decbdb44d5f3.png">
Even though pops up error when creating app, the app is showed in apps tab, but I can't edit nor to do anything about it
<img width="955" alt="image" src="https://user-images.githubusercontent.com/16564571/186322644-edc3b20f-bafe-418b-8c1d-59dcf716525b.png">

**Comment by Rory-Powell** [comment]
Hi @marcogutama , sorry we didn't get back to you sooner on this one. Are you still experiencing issues? We resolved the problem that was causing the error in your first screenshot

**Comment by marcogutama** [comment]
Hello @Rory-Powell. Yes, the next day I tried again and it was solved. Now I can create and edit apps without problems, thanks.

I'm not sure what the source of the problem would be. Maybe some kind of maintenance just that day at that time.

**Comment by LuD1161** [comment]
I've been trying the same thing and it's showing `access denied`. I am using my company gmail to signup. I also verified my account. Still the same error 🤔 
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/17861054/197194825-86de01bc-f690-47ca-9af6-0512b7345491.png">


I logged out of my account and tried relogging in . No issues there. But when I create an app or *Edit an app* , it shows *Locked by you* and in the error box it shows *Error initialising app: Not Found*

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/17861054/197195250-41f69fea-9b67-4fbf-947f-83b14057b28a.png">
