### ISSUE TITLE
Error initializing the app / error updating the app

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#7395]
**Hosting**
- Cloud v. 1.2.47

**Describe the bug**
Self-explanatory below

**To Reproduce**
1. Log in to Budibase
2. Click "Manage" the app

**Expected behavior**
No errors.

**Screenshots**
![error](https://user-images.githubusercontent.com/94982318/185853878-64a05090-312e-4061-aaac-89f7a7c97614.png)
  
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 104.0.5112.102 (Official Build) (64-bit)

**Additional context**
Updated the app to 1.2.45 on August 19, 2022. Today, on August 22, 2022 it showed "Error initializing app" then when clicked update to 1.2.47 it showed "error updating app".

**Comment by 3699n** [comment]
I have the exact same issue. Unable to edit any of my apps on Budibase cloud.

**Comment by aptkingston** [comment]
We're aware of this and looking into it as top priority.

**Comment by shogunpurple** [comment]
Hi folks - this one should be resolved. Seems to be a temporary infrastructure issue - we are still looking into the root cause but you should be able to load your applications and use bb as normal. Thanks!

**Comment by namas191297** [comment]
I'm still having this issue, unable to load, edit or create new applications.

**Comment by shogunpurple** [comment]
Hi folks, this one should now be resolved.

**Comment by zawiya** [comment]
This has happened to me on self hosting, I've  raise an issue #7395, how was it resolved?
